# NumPy is a numerical processing library that can efficiently handle large data sets stored as arrays

In [3]:
import numpy as np

#### Different ways to create numpy arrays

In [5]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

#### Lets cast a nested list to numpy array

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(mylist) # This creates a two dimensional array/matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mymatrix = np.array(mylist)

In [13]:
mymatrix.shape

(3, 3)

In [14]:
np.arange(0,10) # start is inclusive and end is exclusive

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,20,2) # with a step size of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
np.ones(4) * 100

array([100., 100., 100., 100.])

#### Ability to create specialised arrays

In [23]:
np.linspace(0,10,20) # linearly spaced arrays

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
np.eye(5) # 5 X 5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(4) # random sample over a uniform distribution, between 0 and 1
# Uniform distribution - every number has a uniform probability of getting chosen

array([0.09561006, 0.46927655, 0.51973774, 0.42840191])

In [26]:
np.random.rand(5,5)

array([[0.14106854, 0.32794161, 0.20196254, 0.77596233, 0.71754303],
       [0.66458272, 0.04045357, 0.99029352, 0.90842033, 0.72532295],
       [0.33501133, 0.53096937, 0.24607696, 0.90619995, 0.46603687],
       [0.3964327 , 0.73426253, 0.80002561, 0.0751843 , 0.28097192],
       [0.19449275, 0.84420877, 0.23314215, 0.61510262, 0.41128644]])

In [28]:
np.random.randn(3) # Standard normal distribution , normally distributed around zero. 
# It has a mean of 0 and standard deviation of 1

array([ 0.27105648,  1.0554454 , -0.33161543])

In [29]:
np.random.randint(0,10) # returns a random integer within the range

9

In [30]:
np.random.randint(1,100,10) # 10 random integers between 0 and 100

array([70, 74, 88, 47, 16, 43, 47, 41, 43, 37])

In [31]:
# to get consistent results
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr = np.random.randint(0,50,10)
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

#### some useful attributes and methods of numpy arrays

In [71]:
# create a 3 x 3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr.max()

43

In [39]:
ranarr.min()

1

In [45]:
ranarr.argmax() # index location of max and minimum values

3

In [46]:
ranarr.argmin()

1

#### Numpy Indexing and Selection

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# to get the number in index location 8
arr[8]

8

In [9]:
arr[1:5] # From index 1 to 5

array([1, 2, 3, 4])

In [10]:
arr[:5] # From index 0 (beginning) to 5

array([0, 1, 2, 3, 4])

In [11]:
# from index 5 , all the way to end
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [14]:
new_arr = arr/2
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [21]:
# slice of an array will always point to the original array
slice_arr = arr[:6]
slice_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
# Now if we see the original array, the respective index numbers are also affected
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
# If we do not want the original number to be affected, we should 
# state an explicit copy
arr_copy = arr.copy()
arr_copy[:] = 10000

In [26]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
# Indexing on 2d array

In [73]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,35,40]])

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [33]:
arr_2d.shape

(3, 3)

In [36]:
# to get the first row and first column element
arr_2d[1][1]

25

In [37]:
arr_2d[2][2]

40

In [40]:
# 2d array slicing - first two rows and second column onwards
# 
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
# one more 2d array slicing
arr_2d[1:,:2]

array([[20, 25],
       [30, 35]])

In [42]:
# conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# to get all elements greater than 4
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr > 4

In [45]:
# now we will do conditional selection by passing boolean array into the original array

In [47]:
# will only return back array elements for which the boolean conditions are true
arr[bool_arr] 

array([ 5,  6,  7,  8,  9, 10])

In [48]:
# The short way of doing it is
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr [arr <= 6]

array([1, 2, 3, 4, 5, 6])

#### NumPy operations

In [51]:
arr = np.arange(0,10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [54]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [55]:
(arr + 2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [56]:
# we can also do this arithmetic operations on two arrays of the same shape
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
1/arr

/Users/suvosmac/anaconda3/envs/timeseries/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [58]:
arr/arr

/Users/suvosmac/anaconda3/envs/timeseries/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [60]:
np.log(arr)

/Users/suvosmac/anaconda3/envs/timeseries/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
arr.sum()

45

In [64]:
arr.mean()

4.5

In [65]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [66]:
arr_2d.shape

(3, 4)

In [67]:
arr_2d.sum()

78

In [68]:
# if we do the sum of all the rows - give me the sum across the rows
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [69]:
arr_2d.sum(axis=0).shape

(4,)

In [70]:
arr_2d.sum(axis=1) # across the columns

array([10, 26, 42])