# Pytorch Tensor Basics

In [1]:
# Import libraries

import numpy as np
import torch

In [2]:
print(f"Torch version used - {torch.__version__}")

Torch version used - 1.9.1


## Converting NumPy arrays to PyTorch tensors¶
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
Calculations between tensors can only happen if the tensors share the same dtype.
In some cases tensors are used as a replacement for NumPy to use the power of GPUs (more on this later).

In [3]:
# Creating a numpy array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Converting this numpy array to tensor
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [5]:
# Another option for conversion
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
# In order to explicityly check for the datatype
x = torch.as_tensor(arr)
x.dtype

torch.int32

In [7]:
# Make a 2D numpy array
arr2d = np.arange(0.0, 12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
# converting it to a 4 X 3 array
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [9]:
# converting this to tensor
x2 = torch.from_numpy(arr2d)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


Here torch.DoubleTensor refers to 64-bit floating point data.

<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

## Copying vs. sharing

- torch.from_numpy()
- torch.as_tensor()
- torch.tensor()

There are a number of different functions available for creating tensors. When using torch.from_numpy() and torch.as_tensor(), the PyTorch tensor and the source NumPy array share the same memory. This means that changes to one affect the other. However, the torch.tensor() function always makes a copy.

In [10]:
# Using torch.from_numpy()

# This creates a tensor pointed to the numpy array
arr = np.arange(0, 5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [11]:
arr[2] = 77
print(t)

tensor([ 0,  1, 77,  3,  4], dtype=torch.int32)


In [12]:
# using torch.Tensor()

# This creates a tensor copied from the numpy array
arr = np.arange(0, 5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [13]:
arr[2] = 77
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


## Class constructors
- torch.Tensor()
- torch.FloatTensor()
- torch.LongTensor(), etc.

There's a subtle difference between using the factory function torch.tensor(data) and the class constructor torch.Tensor(data).
The factory function determines the dtype from the incoming data, or from a passed-in dtype argument.
The class constructor torch.Tensor()is simply an alias for torch.FloatTensor(data). Consider the following:

In [14]:
data = np.array([1, 2, 3, 4])

a = torch.Tensor(data)
print(a, a.type())

tensor([1., 2., 3., 4.]) torch.FloatTensor


In [15]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3, 4], dtype=torch.int32) torch.IntTensor


In [16]:
c = torch.tensor(data=data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3, 4]) torch.LongTensor


## Creating tensors from scratch
### Uninitialized tensors with .empty()

torch.empty() returns an uninitialized tensor. Essentially a block of memory is allocated according to the size of the tensor, and any values already sitting in the block are returned.<br> 
This is similar to the behavior of numpy.empty().

In [18]:
x = torch.empty(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Initialized tensors with .zeros() and .ones()
- torch.zeros(size)
- torch.ones(size) <br>
It's a good idea to pass in the intended dtype.

In [20]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


### Tensors from ranges
- torch.arange(start,end,step)
- torch.linspace(start,end,steps) <br>
Note that with .arange(), end is exclusive, while with linspace(), end is inclusive.

In [21]:
x = torch.arange(0, 18, 2).reshape(3, 3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [22]:
x = torch.linspace(0, 18, 12).reshape(3, 4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


### Tensors from data
torch.tensor() will choose the dtype based on incoming data:

In [23]:
x = torch.tensor([1, 2, 3, 4]).reshape(2, 2)
print(x)
print(x.dtype)
print(x.type())

tensor([[1, 2],
        [3, 4]])
torch.int64
torch.LongTensor


Alternatively you can set the type by the tensor method used. For a list of tensor types visit https://pytorch.org/docs/stable/tensors.html

In [24]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


You can also pass the dtype in as an argument. For a list of dtypes visit https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype

In [25]:
x = torch.tensor([8, 9, -3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


### Changing the dtype of existing tensors
Don't be tempted to use x = torch.tensor(x, dtype=torch.type) as it will raise an error about improper use of tensor cloning.
Instead, use the tensor .type() method.

In [27]:
print('Old :', x.type())
x = x.type(torch.int64)
print('New :', x.type())

Old : torch.IntTensor
New : torch.LongTensor


## Random number tensors
- torch.rand(size) returns random samples from a uniform distribution over [0, 1)
- torch.randn(size) returns samples from the "standard normal" distribution [σ = 1]<br>
    Unlike rand which is uniform, values closer to zero are more likely to appear.<br>
- torch.randint(low,high,size) returns random integers from low (inclusive) to high (exclusive)

In [28]:
x = torch.rand(4, 3)
print(x)

tensor([[0.2154, 0.8994, 0.6040],
        [0.4130, 0.7831, 0.0535],
        [0.2804, 0.8563, 0.7606],
        [0.0377, 0.5664, 0.8884]])


In [29]:
x = torch.randn(4, 3)
print(x)

tensor([[ 0.1452, -0.4419, -1.0549],
        [-0.6342, -1.3301,  0.3415],
        [ 0.5280, -1.7555,  0.0742],
        [ 0.9813, -0.1466, -0.2471]])


In [30]:
x = torch.randint(0, 5, (4, 3))
print(x)

tensor([[1, 1, 4],
        [2, 0, 2],
        [2, 4, 3],
        [4, 2, 3]])


### Random number tensors that follow the input size
- torch.rand_like(input)
- torch.randn_like(input)
- torch.randint_like(input,low,high)<br>
**these return random number tensors with the same size as input**

In [31]:
x = torch.zeros(2, 5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [32]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.0669,  0.7483, -0.7473, -0.3508,  0.7589],
        [ 1.1151,  1.4999, -0.1359, -1.0160, -0.3819]])


The same syntax can be used with
- torch.zeros_like(input)
- torch.ones_like(input)

In [33]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


### Setting the random seed
torch.manual_seed(int) is used to obtain reproducible results

In [35]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


## Tensor attributes
Besides dtype, we can look at other tensor attributes like shape, device and layout

In [36]:
x.shape

torch.Size([2, 3])

In [37]:
x.size()

torch.Size([2, 3])

In [38]:
x.device

device(type='cpu')

PyTorch has a class to hold the memory layout option. The default setting of strided will suit our purposes throughout the course.

In [45]:
x.layout

torch.strided

## Check gpu availability

In [44]:
print(f"If GPU is available - {torch.cuda.is_available()}")
print(f"The current device being used - {torch.cuda.current_device()}")
print(f"Get the current device name - {torch.cuda.get_device_name()}")

If GPU is available - True
The current device being used - 0
Get the current device name - NVIDIA GeForce RTX 2070 SUPER


In [46]:
x = torch.arange(6).reshape(3, 2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [47]:
# Grabbing the right hand column vectors
x[:, 1]

tensor([1, 3, 5])

In [49]:
# Grabbing the right hand column as a (3,1) slice
x[:, 1:]

tensor([[1],
        [3],
        [5]])