# Pytorch Tensor Basics

In [1]:
# Import libraries

import numpy as np
import torch

In [2]:
print(f"Torch version used - {torch.__version__}")

Torch version used - 1.9.1


## Converting NumPy arrays to PyTorch tensors¶
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
Calculations between tensors can only happen if the tensors share the same dtype.
In some cases tensors are used as a replacement for NumPy to use the power of GPUs (more on this later).

In [3]:
# Creating a numpy array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Converting this numpy array to tensor
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [5]:
# Another option for conversion
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
# In order to explicityly check for the datatype
x = torch.as_tensor(arr)
x.dtype

torch.int32

In [7]:
# Make a 2D numpy array
arr2d = np.arange(0.0, 12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
# converting it to a 4 X 3 array
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [10]:
# converting this to tensor
x2 = torch.from_numpy(arr2d)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


Here torch.DoubleTensor refers to 64-bit floating point data.

<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>

## Copying vs. sharing

- torch.from_numpy()
- torch.as_tensor()
- torch.tensor()

There are a number of different functions available for creating tensors. When using torch.from_numpy() and torch.as_tensor(), the PyTorch tensor and the source NumPy array share the same memory. This means that changes to one affect the other. However, the torch.tensor() function always makes a copy.

In [11]:
# Using torch.from_numpy()

# This creates a tensor pointed to the numpy array
arr = np.arange(0, 5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [12]:
arr[2] = 77
print(t)

tensor([ 0,  1, 77,  3,  4], dtype=torch.int32)


In [15]:
# using torch.Tensor()

# This creates a tensor copied from the numpy array
arr = np.arange(0, 5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [14]:
arr[2] = 77
print(t)

tensor([0., 1., 2., 3., 4.])


## Class constructors
- torch.Tensor()
- torch.FloatTensor()
- torch.LongTensor(), etc.

There's a subtle difference between using the factory function torch.tensor(data) and the class constructor torch.Tensor(data).
The factory function determines the dtype from the incoming data, or from a passed-in dtype argument.
The class constructor torch.Tensor()is simply an alias for torch.FloatTensor(data). Consider the following:

In [16]:
data = np.array([1, 2, 3, 4])

a = torch.Tensor(data)
print(a, a.type())

tensor([1., 2., 3., 4.]) torch.FloatTensor


In [17]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3, 4], dtype=torch.int32) torch.IntTensor


In [18]:
c = torch.tensor(data=data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3, 4]) torch.LongTensor


## Creating tensors from scratch
### Uninitialized tensors with .empty()

torch.empty() returns an uninitialized tensor. Essentially a block of memory is allocated according to the size of the tensor, and any values already sitting in the block are returned. This is similar to the behavior of numpy.empty().