## Basics of TensorFlow 2.0

* Constants, Variables, Tensors
* Operations with Tensors
* Strings

### What is a Tensor?

A tensor is often thought of as a generalized matrix. That is, it could be a 1-D matrix (a vector is actually such a tensor), a 3-D matrix (something like a cube of numbers), even a 0-D matrix (a single number), or a higher dimensional structure that is harder to visualize. The dimension of the tensor is called its rank.

A tensor is a container which can house data in N dimensions, along with its linear operations.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# Let's check the version
print(f"Tensorflow Version - {tf.__version__}")

Tensorflow Version - 2.4.1


### Constants

In [3]:
# Define a constant
tensor = tf.constant([[23, 4], [32, 51]])

# to get values of tensor
tensor

2022-07-14 20:23:50.181185: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [4]:
# to get the dimensions of the tensor
tensor.shape

TensorShape([2, 2])

In [7]:
# to get only the values of the tensor
tensor.numpy() # Returns a numpy array


array([[23,  4],
       [32, 51]], dtype=int32)

In [9]:
# We can convert a numpy array to a tensor as well
numpy_tensor = np.array([[23, 24], [25, 26]])
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23, 24],
       [25, 26]])>

### Variables

In [10]:
tf_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [11]:
# In order to get the values of the variable only
tf_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [12]:
# Changing specific values of the variable - for example if we need to change - first row and third column
tf_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [13]:
# now check the value
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operations with Tensors

In [14]:
# Declare a tensor object

tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [15]:
# Addition between a scalar and a tensor
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [16]:
# Multiplication between a tensor and a scalar
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [17]:
# we can use numpy functions on tensors as well
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [18]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [19]:
# dot product between two tensors
np.dot(tensor, numpy_tensor) # It will perform matrix product

array([[ 73,  76],
       [169, 176]])

### Strings in Tensor flow 2.0

In [20]:
# Create a string in tensor flow

tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

In [21]:
# Find the length of the string

tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [22]:
# to get the unicode for each of the characters in the string
tf.strings.unicode_decode(tf_string, 'UTF8')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

In [23]:
# to get the value for the particular character - F
tf.strings.unicode_decode(tf_string, 'UTF8').numpy()[6]

70

In [24]:
# Storing array of strings
tf_string_array = tf.constant(['tensorflow', 'Deep Learning', 'AI'])

# to print the individual element from the array

for string in tf_string_array:
    print(string)

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
